# frozen_string_literal: true

require_relative "../ipam"

module Naaf
  module Renderers
    module Nftables
      def self.render(db)
        s = Naaf.settings
        wg = s[:wg_interface]
        wan = s[:wan_interface]
        net = s[:wg_subnet]

        enabled = db[:clients].where(enabled: true).to_a
        by_id = enabled.to_h { |c| [c[:id], c] }
        site_nets, site_nat = site_forwarding(db, wg, net)

        tcp_allow = []
        udp_allow = []
        db[:exposed_ports].each do |e|
          c = by_id[e[:client_id]] or next
          ((e[:proto] == "udp") ? udp_allow : tcp_allow) <<
            [c[:wg_ip], e[:port], e[:port_end] || e[:port]]
        end
        tcp_allow = merge(tcp_allow)
        udp_allow = merge(udp_allow)

        dnat = db[:port_forwards].where(enabled: true).map do |f|
          c = by_id[f[:client_id]] or next
          "    iifname \"#{wan}\" #{f[:proto]} dport #{f[:public_port]} " \
            "dnat ip to #{c[:wg_ip]}:#{f[:target_port]}"
        end.compact

        <<~NFT
          # Generated by naaf. Applied atomically. Do not edit by hand.
          # The static base firewall lives in /etc/nftables.conf (table inet filter)
          # and is NEVER touched by this application.
          table inet naaf {}
          delete table inet naaf

          table inet naaf {
            set vpn_tcp_allow {
              type ipv4_addr . inet_service
              flags interval
              #{elements(tcp_allow)}
            }

            set vpn_udp_allow {
              type ipv4_addr . inet_service
              flags interval
              #{elements(udp_allow)}
            }

            set site_nets {
              type ipv4_addr
              flags interval
              #{elements(site_nets)}
            }

            chain forward {
              type filter hook forward priority filter; policy accept;

              # --- spoke <-> spoke: default deny, allow only declared ports ---
              iifname "#{wg}" oifname "#{wg}" ct state established,related accept
              iifname "#{wg}" oifname "#{wg}" icmp type echo-request accept
              iifname "#{wg}" oifname "#{wg}" ip daddr . tcp dport @vpn_tcp_allow accept
              iifname "#{wg}" oifname "#{wg}" ip daddr . udp dport @vpn_udp_allow accept
              # site LANs ride the same interface; accept them before the drop
              iifname "#{wg}" oifname "#{wg}" ip daddr @site_nets accept
              iifname "#{wg}" oifname "#{wg}" ip saddr @site_nets accept
              iifname "#{wg}" oifname "#{wg}" counter drop

              # --- inbound DNAT traffic from the public side ---
              iifname "#{wan}" oifname "#{wg}" ct state established,related accept
              iifname "#{wan}" oifname "#{wg}" ct status dnat accept
            }

            chain prerouting {
              type nat hook prerouting priority dstnat; policy accept;
          #{dnat.join("\n")}
            }

            chain postrouting {
              type nat hook postrouting priority srcnat; policy accept;

              # full-tunnel egress to the internet
              ip saddr #{net} oifname "#{wan}" masquerade

              # DNAT hairpin: make the client reply via the hub, not its own
              # default route (critical for split-tunnel clients)
              oifname "#{wg}" ct status dnat masquerade
          #{site_nat}
            }
          }
        NFT
      end

      # Enabled sites' CIDRs (merged so the interval set cannot reject them)
      # and optional SNAT lines for sites that cannot put wg_subnet in the
      # remote AllowedIPs. One rule per masquerading site.
      def self.site_forwarding(db, wg, net)
        cidrs = []
        nat = []
        db[:sites].where(enabled: true).order(:name).each do |site|
          nets = db[:site_networks].where(site_id: site[:id]).order(:cidr).select_map(:cidr)
          cidrs.concat(nets)
          next unless site[:masquerade] && nets.any?
          merged = IPAM.merge_v4_cidrs(nets)
          dest = (merged.size == 1) ? merged.first : "{ #{merged.join(", ")} }"
          nat << if site[:address]
            "    ip saddr #{net} ip daddr #{dest} oifname \"#{wg}\" snat to #{site[:address]}"
          else
            "    ip saddr #{net} ip daddr #{dest} oifname \"#{wg}\" masquerade"
          end
        end
        [IPAM.merge_v4_cidrs(cidrs), nat.join("\n")]
      end

      # Collapse [ip, first, last] triples into sorted nft set elements, merging
      # ranges that overlap or touch on the same address.
      #
      # The merge is not cosmetic. An `flags interval` set rejects overlapping
      # elements outright, and the whole ruleset is applied as one `nft -f`
      # transaction — so a single overlapping pair would fail *every* apply, not
      # just the offending rule. The UI refuses overlaps on insert, but the DB
      # cannot express that constraint, so the renderer stays total: any set of
      # rows in, valid ruleset out.
      #
      # A single port emits as a bare `ip . port`, which an interval set reads as
      # a degenerate range.
      def self.merge(entries)
        entries.group_by(&:first).sort.flat_map do |ip, rows|
          rows.map { |(_, first, last)| [first, last] }.sort
            .each_with_object([]) { |(first, last), acc|
              if acc.any? && first <= acc.last[1] + 1
                acc.last[1] = last if last > acc.last[1]
              else
                acc << [first, last]
              end
            }
            .map { |(first, last)| (first == last) ? "#{ip} . #{first}" : "#{ip} . #{first}-#{last}" }
        end
      end

      def self.elements(list)
        return "" if list.empty?
        "elements = { #{list.join(", ")} }"
      end
    end
  end
end
