# frozen_string_literal: true

require "ipaddr"

module Naaf
  module Renderers
    module WireGuard
      def self.render(db)
        s = Naaf.settings
        prefix = IPAddr.new(s[:wg_subnet]).prefix

        out = +"# Generated by naaf. Do not edit by hand.\n[Interface]\n"
        out << "Address = #{s[:server_ip]}/#{prefix}\n"
        out << "ListenPort = #{s[:listen_port]}\n"
        out << "PrivateKey = #{s[:server_privkey]}\n"
        out << "MTU = #{s[:mtu]}\n"

        db[:clients].where(enabled: true).order(:wg_ip).each do |c|
          out << "\n[Peer]\n"
          out << "# #{c[:name]} (#{c[:hostname]})\n"
          out << "PublicKey = #{c[:pubkey]}\n"
          out << "PresharedKey = #{c[:psk]}\n"
          out << "AllowedIPs = #{c[:wg_ip]}/32\n"
        end

        # A site is a remote WireGuard server we dial. AllowedIPs are the
        # remote LANs (cryptokey routing), not a /32 on wg_subnet. A peer
        # with no networks is omitted: WireGuard refuses an empty AllowedIPs.
        db[:sites].where(enabled: true).order(:name).each do |site|
          cidrs = db[:site_networks].where(site_id: site[:id]).order(:cidr).select_map(:cidr)
          next if cidrs.empty?
          out << "\n[Peer]\n"
          out << "# #{site[:name]} (site)\n"
          out << "PublicKey = #{site[:pubkey]}\n"
          out << "PresharedKey = #{site[:psk]}\n" if site[:psk]
          out << "AllowedIPs = #{cidrs.join(", ")}\n"
          out << "Endpoint = #{site[:endpoint]}\n"
          out << "PersistentKeepalive = #{site[:keepalive]}\n"
        end
        out
      end
    end
  end
end
