# frozen_string_literal: true

require "ipaddr"

module Naaf
  module Renderers
    module WireGuard
      def self.render(db)
        s = Naaf.settings
        prefix = IPAddr.new(s[:wg_subnet]).prefix

        out = +"# Generated by naaf. Do not edit by hand.\n[Interface]\n"
        out << "Address = #{s[:server_ip]}/#{prefix}\n"
        out << "ListenPort = #{s[:listen_port]}\n"
        out << "PrivateKey = #{s[:server_privkey]}\n"
        out << "MTU = #{s[:mtu]}\n"

        db[:clients].where(enabled: true).order(:wg_ip).each do |c|
          out << "\n[Peer]\n"
          out << "# #{c[:name]} (#{c[:hostname]})\n"
          out << "PublicKey = #{c[:pubkey]}\n"
          out << "PresharedKey = #{c[:psk]}\n"
          out << "AllowedIPs = #{c[:wg_ip]}/32\n"
        end
        out
      end
    end
  end
end
