#!/usr/bin/env bash
# Install /etc/naaf/naaf.conf from the operator's naaf.conf, read on STDIN.
# Runs ON the box as root; deploy.sh pipes the file in (workstation-only section
# already stripped). Takes the service group as $1.
#
# Merge rule: a key left EMPTY in the incoming file never overwrites a non-empty
# value already on the box.
#
# An empty value means "unset — fall through to the default", so treating it as
# "set this to nothing" destroys the two values that are written on the box
# rather than by hand:
#
#   NAAF_SESSION_SECRET  generated by 40-app.sh on first deploy. Blanking it
#                        makes the app die at boot with KeyError, and
#                        regenerating it invalidates every admin session.
#   NAAF_ENDPOINT_HOST   written back by 50-bringup.sh when it is passed for a
#                        run, so the file keeps matching what clients dial.
#
# Both are blank in naaf.conf.example, so without this every re-deploy of a
# healthy box would clobber them.
set -euo pipefail

# Overridable only so the merge can be exercised without root; production always
# takes the default.
CONF="${NAAF_CONF_PATH:-/etc/naaf/naaf.conf}"
GROUP="${1:-naaf}"

incoming="$(mktemp)"
merged="$(mktemp)"
trap 'rm -f "$incoming" "$merged"' EXIT
cat >"$incoming"

[ -s "$incoming" ] || { echo "install-config: empty input, refusing to write $CONF" >&2; exit 1; }

kept=()
while IFS= read -r line; do
  # Comments, blanks and anything that is not KEY=value pass through untouched.
  case "$line" in
    [A-Za-z_]*=*) ;;
    *) printf '%s\n' "$line"; continue ;;
  esac
  k="${line%%=*}"
  v="${line#*=}"
  if [ -z "$v" ] && [ -f "$CONF" ]; then
    cur="$(sed -n "s/^$k=//p" "$CONF" | head -1)"
    if [ -n "$cur" ]; then
      printf '%s=%s\n' "$k" "$cur"
      kept+=("$k")
      continue
    fi
  fi
  printf '%s\n' "$line"
done <"$incoming" >"$merged"

[ "${#kept[@]}" -eq 0 ] || echo "install-config: kept the box's value for ${kept[*]}" >&2

install -d -m 0750 "$(dirname "$CONF")"
# Write via a temp in the same directory so a reader never sees a partial file,
# and so a failure leaves the previous config in place.
install -m 0640 "$merged" "$CONF.tmp"
# The group only exists once 20-system.sh has run. Before that, root-only is the
# safe direction to be wrong in — this file carries the session secret — and
# 40-app.sh enforces the final ownership on every run either way.
if [ "$(id -u)" -eq 0 ]; then
  if getent group "$GROUP" >/dev/null 2>&1; then
    chown root:"$GROUP" "$CONF.tmp"
  else
    chown root:root "$CONF.tmp"
  fi
fi
mv "$CONF.tmp" "$CONF"
