# frozen_string_literal: true

module WGCP
  module Renderers
    module Nftables
      def self.render(db)
        s = WGCP.settings
        wg = s[:wg_interface]
        wan = s[:wan_interface]
        net = s[:wg_subnet]

        enabled = db[:clients].where(enabled: true).to_a
        by_id = enabled.to_h { |c| [c[:id], c] }

        tcp_allow = []
        udp_allow = []
        db[:exposed_ports].each do |e|
          c = by_id[e[:client_id]] or next
          ((e[:proto] == "udp") ? udp_allow : tcp_allow) <<
            [c[:wg_ip], e[:port], e[:port_end] || e[:port]]
        end
        tcp_allow = merge(tcp_allow)
        udp_allow = merge(udp_allow)

        dnat = db[:port_forwards].where(enabled: true).map do |f|
          c = by_id[f[:client_id]] or next
          "    iifname \"#{wan}\" #{f[:proto]} dport #{f[:public_port]} " \
            "dnat ip to #{c[:wg_ip]}:#{f[:target_port]}"
        end.compact

        <<~NFT
          # Generated by wgcp. Applied atomically. Do not edit by hand.
          # The static base firewall lives in /etc/nftables.conf (table inet filter)
          # and is NEVER touched by this application.
          table inet wgcp {}
          delete table inet wgcp

          table inet wgcp {
            set vpn_tcp_allow {
              type ipv4_addr . inet_service
              flags interval
              #{elements(tcp_allow)}
            }

            set vpn_udp_allow {
              type ipv4_addr . inet_service
              flags interval
              #{elements(udp_allow)}
            }

            chain forward {
              type filter hook forward priority filter; policy accept;

              # --- spoke <-> spoke: default deny, allow only declared ports ---
              iifname "#{wg}" oifname "#{wg}" ct state established,related accept
              iifname "#{wg}" oifname "#{wg}" icmp type echo-request accept
              iifname "#{wg}" oifname "#{wg}" ip daddr . tcp dport @vpn_tcp_allow accept
              iifname "#{wg}" oifname "#{wg}" ip daddr . udp dport @vpn_udp_allow accept
              iifname "#{wg}" oifname "#{wg}" counter drop

              # --- inbound DNAT traffic from the public side ---
              iifname "#{wan}" oifname "#{wg}" ct state established,related accept
              iifname "#{wan}" oifname "#{wg}" ct status dnat accept
            }

            chain prerouting {
              type nat hook prerouting priority dstnat; policy accept;
          #{dnat.join("\n")}
            }

            chain postrouting {
              type nat hook postrouting priority srcnat; policy accept;

              # full-tunnel egress to the internet
              ip saddr #{net} oifname "#{wan}" masquerade

              # DNAT hairpin: make the client reply via the hub, not its own
              # default route (critical for split-tunnel clients)
              oifname "#{wg}" ct status dnat masquerade
            }
          }
        NFT
      end

      # Collapse [ip, first, last] triples into sorted nft set elements, merging
      # ranges that overlap or touch on the same address.
      #
      # The merge is not cosmetic. An `flags interval` set rejects overlapping
      # elements outright, and the whole ruleset is applied as one `nft -f`
      # transaction — so a single overlapping pair would fail *every* apply, not
      # just the offending rule. The UI refuses overlaps on insert, but the DB
      # cannot express that constraint, so the renderer stays total: any set of
      # rows in, valid ruleset out.
      #
      # A single port emits as a bare `ip . port`, which an interval set reads as
      # a degenerate range.
      def self.merge(entries)
        entries.group_by(&:first).sort.flat_map do |ip, rows|
          rows.map { |(_, first, last)| [first, last] }.sort
            .each_with_object([]) { |(first, last), acc|
              if acc.any? && first <= acc.last[1] + 1
                acc.last[1] = last if last > acc.last[1]
              else
                acc << [first, last]
              end
            }
            .map { |(first, last)| (first == last) ? "#{ip} . #{first}" : "#{ip} . #{first}-#{last}" }
        end
      end

      def self.elements(list)
        return "" if list.empty?
        "elements = { #{list.join(", ")} }"
      end
    end
  end
end
