#!/usr/bin/env bash
# Optional continuous replication of the SQLite database. No-op unless
# NAAF_LITESTREAM_ENABLED=1, so the step list stays constant either way.
#
# Installs the pinned .deb straight from the GitHub release. Litestream publishes
# no apt repository, so this adds zero signing keys and zero sources.list entries
# — the usual objection to third-party apt does not apply. The .deb also brings
# the maintained litestream.service, so we ship a small drop-in rather than a
# whole unit we would have to keep in step with upstream's ExecStart forever.
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=00-lib.sh
source "$DIR/00-lib.sh"
require_root

if [ "${NAAF_LITESTREAM_ENABLED:-0}" != "1" ]; then
  log "NAAF_LITESTREAM_ENABLED is not 1 — skipping replication setup"
  systemctl disable --now litestream 2>/dev/null || true
  exit 0
fi

VER="${NAAF_LITESTREAM_VERSION:-}"
if [ -z "$VER" ]; then
  VER="$(curl -fsSL https://api.github.com/repos/benbjohnson/litestream/releases/latest |
    jq -r '.tag_name' | sed 's/^v//')"
fi
[ -n "$VER" ] || die "could not resolve a litestream version"

# The release assets use x86_64/arm64, NOT Debian's amd64/armhf, and the version
# in the filename carries no leading v even though the tag does.
case "$(dpkg --print-architecture)" in
  amd64) LSARCH=x86_64 ;;
  arm64) LSARCH=arm64  ;;
  armhf) LSARCH=armv7  ;;
  *) die "no litestream release for architecture $(dpkg --print-architecture)" ;;
esac

if ! command -v litestream >/dev/null 2>&1 || ! litestream version 2>/dev/null | grep -q "$VER"; then
  base="https://github.com/benbjohnson/litestream/releases/download/v$VER"
  deb="litestream-$VER-linux-$LSARCH.deb"
  tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
  log "downloading $deb"
  curl -fsSL -o "$tmp/$deb" "$base/$deb"
  curl -fsSL -o "$tmp/checksums.txt" "$base/checksums.txt"
  (cd "$tmp" && grep " $deb\$" checksums.txt | sha256sum -c -) ||
    die "checksum mismatch for $deb — refusing to install"
  dpkg -i "$tmp/$deb"
fi
log "litestream $(litestream version)"

REPLICA_TYPE="${NAAF_LITESTREAM_REPLICA_TYPE:-file}"
SNAP_INTERVAL="${NAAF_LITESTREAM_SNAPSHOT_INTERVAL:-24h}"
SNAP_RETENTION="${NAAF_LITESTREAM_SNAPSHOT_RETENTION:-168h}"
REPLICA_PATH="${NAAF_LITESTREAM_PATH:-$NAAF_STATE_DIR/replica}"

# Credentials live in their own file, NOT naaf.conf: that one is EnvironmentFile=
# for naaf.service, so anything in it becomes an environment variable of the
# tunnel-facing web application. Litestream reads these two names from its own
# environment and expands them in the config, so the keys never touch the YAML.
CRED_ENV=/etc/naaf/litestream.env
if [ -n "${NAAF_LITESTREAM_ACCESS_KEY_ID:-}" ]; then
  log "writing $CRED_ENV"
  umask 027
  cat >"$CRED_ENV" <<EOF
LITESTREAM_ACCESS_KEY_ID=$NAAF_LITESTREAM_ACCESS_KEY_ID
LITESTREAM_SECRET_ACCESS_KEY=${NAAF_LITESTREAM_SECRET_ACCESS_KEY:-}
EOF
  chown root:"$NAAF_GROUP" "$CRED_ENV"
  chmod 0640 "$CRED_ENV"
fi

log "writing /etc/litestream.yml ($REPLICA_TYPE replica)"
{
  cat <<EOF
# Generated by deploy/provision/45-litestream.sh from naaf.conf.
# Do not edit by hand — re-run that step instead.
logging:
  level: info
  type: text

snapshot:
  interval: $SNAP_INTERVAL
  retention: $SNAP_RETENTION

dbs:
  # \`path:\`, never \`dir:\`/\`pattern:\` — a directory scan would find the periodic
  # VACUUM INTO snapshots in $NAAF_BACKUP_DIR and try to replicate those too.
  - path: $NAAF_DB
    meta-path: $NAAF_STATE_DIR/.naaf.db-litestream
    # Pairs with PRAGMA busy_timeout = 5000 in lib/naaf/db.rb. Keep them in step.
    busy-timeout: 5s
    replica:
EOF
  if [ "$REPLICA_TYPE" = "file" ]; then
    cat <<EOF
      type: file
      path: $REPLICA_PATH
      sync-interval: 1s
EOF
  else
    : "${NAAF_LITESTREAM_BUCKET:?set NAAF_LITESTREAM_BUCKET for an s3 replica}"
    cat <<EOF
      type: s3
      bucket: $NAAF_LITESTREAM_BUCKET
      path: ${NAAF_LITESTREAM_PREFIX:-naaf}
      sync-interval: 1s
EOF
    [ -n "${NAAF_LITESTREAM_REGION:-}" ] &&
      printf '      region: %s\n' "$NAAF_LITESTREAM_REGION"
    [ -n "${NAAF_LITESTREAM_ENDPOINT:-}" ] &&
      printf '      endpoint: %s\n' "$NAAF_LITESTREAM_ENDPOINT"
    if [ -n "${NAAF_LITESTREAM_ACCESS_KEY_ID:-}" ]; then
      printf '      access-key-id: ${LITESTREAM_ACCESS_KEY_ID}\n'
      printf '      secret-access-key: ${LITESTREAM_SECRET_ACCESS_KEY}\n'
    fi
  fi
} >/etc/litestream.yml
chown root:"$NAAF_GROUP" /etc/litestream.yml
chmod 0640 /etc/litestream.yml

if [ "$REPLICA_TYPE" = "file" ]; then
  install -d -o "$NAAF_USER" -g "$NAAF_GROUP" -m 0700 "$REPLICA_PATH"
fi

# The packaged unit runs litestream as root. Litestream writes the database's own
# metadata and creates the -wal/-shm files when they are absent, so as root it
# would leave root-owned files in a 0750 naaf:naaf directory and the app would
# fail to write to its own database on the next restart — silently, weeks later.
# Run it as the database's owner instead.
#
# A drop-in, not our own unit: a competing /etc/systemd/system/litestream.service
# would shadow the packaged one and silently diverge from upstream's ExecStart
# across versions. `systemctl cat litestream` shows both.
log "installing the litestream drop-in (User=$NAAF_USER)"
install -d -m 0755 /etc/systemd/system/litestream.service.d
{
  cat <<EOF
# Installed by deploy/provision/45-litestream.sh. See docs/BACKUP.md.
[Unit]
# Wants=, never Requires=: replication must never be able to take the VPN down.
After=naaf.service
Wants=naaf.service

[Service]
User=$NAAF_USER
Group=$NAAF_GROUP
EnvironmentFile=-$CRED_ENV
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
PrivateTmp=yes
ReadWritePaths=$NAAF_STATE_DIR
EOF
  # A replica outside the state dir needs its own write permission, or the
  # sandbox denies it with an error that looks nothing like its cause.
  case "$REPLICA_PATH" in
    "$NAAF_STATE_DIR"/*) ;;
    *) [ "$REPLICA_TYPE" = "file" ] && printf 'ReadWritePaths=%s\n' "$REPLICA_PATH" ;;
  esac
} >/etc/systemd/system/litestream.service.d/10-naaf.conf

systemctl daemon-reload
systemctl enable --now litestream
systemctl --no-pager --lines=0 status litestream || true
log "replication enabled — verify with: litestream databases; litestream snapshots $NAAF_DB"
